### ISSUE TITLE
bug: เมื่อคลิก 'ดูทั้งหมด' ควรnavigateไปเริ่มที่ด้านบนสุดของหน้าสรุปผลการลงมติ

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/they-work-for-us#56] opened 2023-03-22 03:28 UTC
https://user-images.githubusercontent.com/123941533/226794705-14e0f82d-d15a-4b24-abb9-88c8721495be.mp4

**Comment by vachirachat** [comment] 2023-03-22 17:05
No sure that I understand requirement correctly. But I fix code to be like this.

https://user-images.githubusercontent.com/42512092/226981833-9d89db2a-ed99-4d57-9ef7-f8241bd680a0.mov


This is all code change. If you have any concern or any suggestion, please let me know.

![Screenshot 2566-03-23 at 00 03 45](https://user-images.githubusercontent.com/42512092/226982485-bc1be2c1-9298-4476-97b0-b12ccb68a480.png)

Thanks.

**Comment by namsaisup** [comment] 2023-04-21 23:12
ถูกค่า

**Comment by Th1nkK1D** [comment] 2023-05-17 08:34
@vachirachat thank you for pointing out where the issue is. I decided to remove the whole `gatsby-browser.js` file to use the default web browser scroll behavior.

Fixed in f8b613797674f9f543f2de7fe4f55532c60df15a

**Closed by Th1nkK1D** 2023-05-17 08:34 UTC
Labels: help wanted
